service: app

provider:
    name: aws
    region: us-east-1

plugins:
    - ./vendor/bref/bref

functions:
    hello:
        handler: index.php
        description: ''
        runtime: php-82

# Exclude files from deployment
package:
    patterns:
        - '!tests/**'
